[files]
exclude = ["managed/**/modify_*.toml", "mise.lock", "uv.lock"]

[format.rules]
indent-width = 4
line-width = 100
trailing-comment-space-width = 1

[[schemas]]
path = "tombi://www.schemastore.org/pyproject.json"
include = ["pyproject.toml"]
format.rules.array-values-order.enabled = true
format.rules.table-keys-order.enabled = true
