---
extends: relaxed

ignore: |
  .cache/
  .local/
  .venv/
  node_modules/
  pnpm-lock.yaml

rules:
  anchors:
    forbid-duplicated-anchors: true
    forbid-undeclared-aliases: true
    forbid-unused-anchors: false
  braces: disable
  brackets: disable
  colons: disable
  commas: disable
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start:
    present: true
  empty-lines: disable
  empty-values: disable
  hyphens: disable
  indentation: disable
  key-duplicates: enable
  line-length: disable
  new-line-at-end-of-file: disable
  new-lines: disable
  octal-values:
    forbid-explicit-octal: true
    forbid-implicit-octal: true
  trailing-spaces: disable
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
