# vim: set filetype=tmux :
# Based on zen tmux configuration
# https://dreamsofcode.io/blog/zen-tmux-configuration

# List of plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "catppuccin/tmux"

# Set catppuccin theme to either latte, frappe, macchiato or mocha
set -g @catppuccin_flavor "mocha"

# Enable 24-bit color support
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -gw xterm-keys on

# Set default shell
set-option -g default-shell "/opt/homebrew/bin/fish"

# Enable mouse control
set -g mouse on

# Vi mode
set-window-option -g mode-keys vi

# Remap prefix from "C-b" to "C-Space"
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# split panes using | and -
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# switch panes using Alt arrow without prefix
unbind M-h 
unbind M-j 
unbind M-k 
unbind M-l 
unbind M-Left
unbind M-Right
unbind M-Up
unbind M-Down
bind -n M-h     select-pane -L \; resize-pane -L -x "60%"
bind -n M-Left  select-pane -L \; resize-pane -L -x "60%"
bind -n M-l     select-pane -R \; resize-pane -R -x "60%"
bind -n M-Right select-pane -R \; resize-pane -R -x "60%"
bind -n M-k     select-pane -U \; resize-pane -U -y "70%"
bind -n M-Up    select-pane -U \; resize-pane -U -y "70%"
bind -n M-j     select-pane -D \; resize-pane -D -y "70%"
bind -n M-Down  select-pane -D \; resize-pane -D -y "70%"

# pass through keys to vim
unbind M-TAB
unbind M-C-TAB
bind -n M-TAB   if-shell "$is_vim" "send-keys M-TAB"   "next-window"
bind -n M-C-TAB if-shell "$is_vim" "send-keys M-C-TAB" "previous-window"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Vim-style copy mode bindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Other key bindings

# Reload tmux config
bind R source-file ~/.config/tmux/tmux.conf \; display-message "Tmux config reloaded!"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
